name: Build and Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    
env:
  SOLUTION_PATH: "./Mando/Mando.sln"

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: "Checkout"
        uses: actions/checkout@v5

      - name: "Install Dotnet"
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "9.0.x"
          
      - name: "Restore dependencies"
        run: dotnet restore ${{ env.SOLUTION_PATH }}
        
      - name: "Build"
        run: dotnet build ${{ env.SOLUTION_PATH }} --no-restore
        
      - name: "Test"
        run: dotnet test ${{ env.SOLUTION_PATH }} --no-build --verbosity normal